title: In The Wake — A Digital Voyage
logo: /assets/img/wake.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
nav:
  - Home: /
  - About: /about/
